/**
 * Write Memo — V3-M4 (Dean & Wiseman execution spec)
 * Spec: docs/specs/intelligence-engine-v3/005_memo_spec.md (Sub-Stage B)
 *
 * Generates the founder-facing strategic memo from the MemoBrief.
 * LLM stage — the writer is a renderer, not a reasoner.
 * All reasoning has been done upstream; the LLM renders it into prose.
 *
 * 7 sections (Dean & Wiseman execution spec):
 *   1. title_block        — code-generated (company name, date, confidential)
 *   2. executive_thesis   — the core contradiction + commercial implication
 *   3. what_we_observed   — 5-7 concrete evidence signals
 *   4. the_pattern        — the underlying system connecting the signals
 *   5. what_this_means    — business impact (trust, conversion, revenue)
 *   6. what_this_changes  — strategic shift (direction, not tactics)
 *   7. cta                — conditional framing, low-friction next step
 *
 * Model: claude-opus-4-6
 * Max tokens: 4000
 * Temperature: 0.5
 *
 * Validation: too_short < 400, too_long > 1400
 *
 * Errors:
 *   ERR_ADJUDICATION_ABORT  — adjudication_mode is "abort"
 *   ERR_MEMO_PARSE          — LLM response is not valid JSON or missing sections
 *   ERR_MEMO_MISSING_SECTIONS — one or more required sections absent
 *   ERR_MEMO_TOO_LONG       — word_count > 1400
 *   ERR_MEMO_TOO_SHORT      — word_count < 400
 *   ERR_MEMO_EVIDENCE_EMPTY — evidence_ids is empty
 *   ERR_BANNED_PHRASE       — banned phrase detected in output
 */

import Anthropic from "@anthropic-ai/sdk";
import type { MemoBrief, MemoSectionName } from "../types/memo-brief.js";
import type { LLMSectionName } from "../types/memo-brief.js";
import type { MarkdownMemo, MemoSection } from "../types/memo.js";
import { countWords } from "./utils.js";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const DEFAULT_MODEL = "claude-opus-4-6";
const DEFAULT_MAX_TOKENS = 4000;
const DEFAULT_TEMPERATURE = 0.5;

export interface WriteMemoConfig {
  model?: string;
  max_tokens?: number;
  temperature?: number;
  /** Injected Anthropic client — used in tests to avoid live API calls */
  client?: Anthropic;
}

// ---------------------------------------------------------------------------
// Section ordering and headings
// ---------------------------------------------------------------------------

/** Sections generated by the LLM (6 keys in JSON output). */
const LLM_SECTION_ORDER: LLMSectionName[] = [
  "executive_thesis",
  "what_we_observed",
  "the_pattern",
  "what_this_means",
  "what_this_changes",
  "cta",
];

/** All 7 memo sections in output order (title_block is code-generated). */
const SECTION_ORDER: MemoSectionName[] = [
  "title_block",
  ...LLM_SECTION_ORDER,
];

const SECTION_HEADINGS: Record<MemoSectionName, string> = {
  title_block: "",  // title_block has no heading — it IS the heading
  executive_thesis: "## Executive Thesis",
  what_we_observed: "## What We Observed",
  the_pattern: "## The Pattern",
  what_this_means: "## What This Means",
  what_this_changes: "## What This Changes",
  cta: "## Next Step",
};

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function findBannedPhrase(text: string, bannedPhrases: string[]): string | null {
  const lower = text.toLowerCase();
  for (const phrase of bannedPhrases) {
    if (lower.includes(phrase.toLowerCase())) {
      return phrase;
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Framing instruction by adjudication_mode
// ---------------------------------------------------------------------------

function framingInstruction(mode: string): string {
  switch (mode) {
    case "full_confidence":
      return "State the diagnosis directly as established fact. Do not hedge. The evidence is strong.";
    case "conditional":
      return "State the diagnosis with confidence, but qualify briefly where evidence is inferred. Be direct where evidence is strong.";
    case "exploratory":
      return "Frame the diagnosis as a hypothesis. Use language like 'the evidence suggests', 'this may indicate', or 'there are signs that'. Do not state anything as established fact.";
    default:
      return "State the diagnosis with care appropriate to the evidence available.";
  }
}

// ---------------------------------------------------------------------------
// System prompt (exported for testing)
// ---------------------------------------------------------------------------

export function buildSystemPrompt(brief: MemoBrief): string {
  const bannedSample = brief.banned_phrases.slice(0, 25).join(", ");
  const caveats =
    brief.confidence_caveats.length > 0
      ? `\nDo not assert the following as established fact: ${brief.confidence_caveats.join("; ")}.`
      : "";

  // V4 system prompt additions — included when synthesis fields are active
  const synthActive =
    brief.synthesised_thesis !== undefined &&
    brief.mechanism_narratives !== undefined &&
    brief.argument_skeleton !== undefined;

  const v4Rules = synthActive
    ? `\n6. The COMPANY-SPECIFIC DIAGNOSTIC STATEMENT names the GTM condition AND its commercial consequence. Use it as-is or paraphrase — do not generalise.\n7. The CAUSAL MECHANISMS are company-specific. Render them; do not rewrite into generic descriptions.\n8. The SUGGESTED ARGUMENT FLOW orders evidence into the strongest logical sequence. Follow unless a superior structure presents itself.\n9. The HOOK STRATEGY tells you what tension to create. Honor the tension_type.`
    : "";

  const hedgingBan =
    brief.adjudication_mode === "full_confidence" || brief.adjudication_mode === "conditional"
      ? `\nHEDGING BAN: Do not use "likely", "may indicate", "could be", "might", "it is possible", "the evidence leaves this open". State findings with the confidence the evidence warrants.`
      : "";

  return `You are writing a Dean & Wiseman strategic diagnostic — a short document that reads like an internal strategy memo that somehow landed on a company founder's desk.

THE THREE EFFECTS — every memo must produce all three:
1. RECOGNITION: "That's uncomfortably accurate"
2. SURPRISE: "I hadn't seen it like that"
3. CURIOSITY: "There's a clear way forward — I want to hear it"

VOICE:
- Internal strategy document tone. Calm. Precise. Observational. Controlled.
- No hype, no flattery, no urgency, no marketing language.
- No first person ("we", "our", "us") anywhere except the final CTA section.
- Every sentence must contain company-specific information.
- Sentence style: short to medium, high clarity, no padding.

SECTION-BY-SECTION GUIDANCE:

executive_thesis (80-130w):
Goal: Define the core contradiction. Create immediate tension. Make the reader continue.
Must contain: surface reality (what it looks like), underlying reality (what is actually happening), commercial implication.
Writing rules: Specific not generic. One idea only. No hedging overload. No buzzwords.
Output standard: Reader should think: "That's uncomfortably accurate."

what_we_observed (180-260w):
Goal: Provide evidence. Prove the thesis is grounded. This is where evidence texture lives.
Must contain: 5-7 concrete signals using only externally visible evidence.
Acceptable evidence: messaging language, offer structure, pricing logic, proof/case studies, reviews, positioning.
Writing rules: Every observation must support thesis. No filler observations. No vague statements. Weave specific language fragments from evidence (review excerpts, pricing page phrasing, job posts) into the analytical narrative — not as block quotes but as texture. Use phrases like "Multiple reviews describe the product as..." or "The pricing page positions..." to embed real evidence.
Output standard: Reader should think: "They've actually looked at this properly."

the_pattern (130-200w):
Goal: Identify the underlying system. Turn observations into insight. This section absorbs the causal reasoning — name what connects the signals and the structural forces at work.
Must contain: One unifying idea. Clear articulation of what connects the signals. The structural forces (2 causal mechanisms) woven into the narrative — not labeled ("First force... Second force...") but felt.
Writing rules: One pattern only. No lists. No multiple interpretations. Must be non-obvious but clearly true.
Output standard: Reader should think: "I hadn't seen it like that."

what_this_means (140-200w):
Goal: Translate insight into business impact.
Must address: trust, conversion, positioning, revenue implication. Name a specific commercial consequence with enough detail that the founder can estimate the cost.
Writing rules: No exaggeration. No precise numbers unless proven. No generic outcomes.
Output standard: Reader should think: "This is likely costing us."

what_this_changes (140-200w):
Goal: Define the strategic shift. Create curiosity.
Must contain: direction of change, reframing of approach.
Must NOT contain: tactics, step-by-step actions, full solution.
Writing rules: Strategic not operational. Clear but incomplete. Controlled specificity. The founder should think "There's a clear way forward" — not "I understand the whole playbook."
Output standard: Reader should think: "There's a clear way forward — I want to hear it."

cta (40-70w):
Goal: Convert interest into conversation.
Must contain: conditional framing ("If this is accurate..."), low-friction next step.
Writing rules: No pressure. No sales language. No "book a call" phrasing. Only section allowed to use first person.
Output standard: Reader should think: "Worth a conversation."

ANALYTICAL DEPTH:
Each section must go one level deeper than the obvious. Executive Thesis names a contradiction AND its commercial implication. What We Observed names signals AND what makes each one unusual. The Pattern names the system AND why it's structurally stable. What This Means names the consequence AND helps the founder estimate the cost. What This Changes names the lever AND implies enough about the resolution to create curiosity.

EVIDENCE TEXTURE:
Weave specific language from evidence into the analytical narrative. Use review excerpts, developer comments, pricing page phrasing, and job post language as texture within sentences — not as standalone quotes. Example: instead of 'Customers value speed', write 'Multiple reviews describe the product as "the fastest way to get a PO signed" — language that never appears on the company's pricing page.' This is the difference between a memo that feels researched and one that feels generated.

READABILITY RHYTHM:
Alternate between analytical sentences and plain-language anchors. After every dense observation, include one short sentence that a non-expert would understand. Dense paragraphs without plain statements lose authority. Short paragraphs (2-3 sentences) between longer ones create pacing.

HARD RULES:
1. Do not invent any facts.
2. Do not use banned phrases: ${bannedSample}.
3. Do not use internal labels ("diagnosis", "mechanism", "intervention", "evidence_spine").
4. Do not open with a compliment, question, or "I wanted to reach out" phrasing.
5. Do not name specific pricing, product tiers, or implementation costs.${caveats}${v4Rules}

${framingInstruction(brief.adjudication_mode)}
${hedgingBan}

WORD BUDGET: Target ${brief.word_budget.target_min}-${brief.word_budget.target_max} words total. Hard maximum: ${brief.word_budget.hard_max}.
Section targets: executive_thesis (80-130w), what_we_observed (180-260w), the_pattern (130-200w), what_this_means (140-200w), what_this_changes (140-200w), cta (40-70w).

OUTPUT FORMAT: Return valid JSON only. No markdown code fences. No text outside the JSON object.
The JSON must have exactly these 6 keys (all required, none empty):
{
  "executive_thesis": "...",
  "what_we_observed": "...",
  "the_pattern": "...",
  "what_this_means": "...",
  "what_this_changes": "...",
  "cta": "..."
}
Each value is the full prose for that section (plain text, use \\n\\n for paragraph breaks within a section).`;
}

// ---------------------------------------------------------------------------
// User prompt (exported for testing)
// ---------------------------------------------------------------------------

export function buildUserPrompt(brief: MemoBrief): string {
  const founderLine = brief.founder_name
    ? `Founder: ${brief.founder_name}${brief.founder_title ? `, ${brief.founder_title}` : ""}\n`
    : "";

  const spineLines = brief.evidence_spine
    .map((r, i) => `  [${i + 1}] "${r.excerpt}"\n      Section guidance: ${r.usage_instruction}`)
    .join("\n");

  // V4 context blocks — built when synthesis fields are present in brief
  const synthActive =
    brief.synthesised_thesis !== undefined &&
    brief.mechanism_narratives !== undefined &&
    brief.argument_skeleton !== undefined &&
    brief.hook_strategy !== undefined;

  const hookStrategyBlock = synthActive
    ? `\nHOOK STRATEGY — understand the strategic intent before rendering:
  Evidence anchor: ${brief.hook_strategy!.evidence_id}
  Tension type: ${brief.hook_strategy!.tension_type}
  Framing instruction: ${brief.hook_strategy!.framing}
  Why this matters to the founder: ${brief.hook_strategy!.why_it_matters}`
    : "";

  const thesisBlock = synthActive
    ? `COMPANY-SPECIFIC DIAGNOSTIC STATEMENT — use this as the thesis:
  ${brief.synthesised_thesis!}
  (This names the specific GTM condition, anchored in an observable company fact,
   and its commercial consequence. Use it as the basis for "what_this_means".
   Do not generalise it.)`
    : `THESIS — the central commercial claim to argue:
${brief.thesis}`;

  const mechanismsBlock =
    synthActive && brief.mechanism_narratives!.length >= 2
      ? `\nCAUSAL MECHANISMS — use these company-specific narratives in "the_pattern":
  Force 1 (${brief.mechanism_narratives![0].mechanism_type}): ${brief.mechanism_narratives![0].company_specific_narrative}
    Evidence: ${brief.mechanism_narratives![0].evidence_refs.join(", ")}
  Force 2 (${brief.mechanism_narratives![1].mechanism_type}): ${brief.mechanism_narratives![1].company_specific_narrative}
    Evidence: ${brief.mechanism_narratives![1].evidence_refs.join(", ")}`
      : "";

  const skeletonBlock =
    synthActive && brief.argument_skeleton!.length > 0
      ? `\nSUGGESTED ARGUMENT FLOW — structure the argument in this order (advisory):\n${
          brief.argument_skeleton!
            .map(
              s =>
                `  Step ${s.step_order} [${s.logical_role}]: Evidence ${s.evidence_id} — ${s.purpose}${s.connector ? ` (${s.connector})` : ""}`
            )
            .join("\n")
        }\n  (The step marked [diagnosis] connects observation and mechanisms into the thesis.)`
      : "";

  let prompt = `Write a 6-section Dean & Wiseman strategic diagnostic for the following company.

COMPANY: ${brief.target_company}
${founderLine}
OPENING HOOK — anchor the Executive Thesis section with this:
Excerpt: "${brief.hook.excerpt}"
Framing instruction: ${brief.hook.framing_instruction}
${hookStrategyBlock}

${thesisBlock}

EVIDENCE SPINE — the only facts you may use (do not invent beyond these):
${spineLines}
${mechanismsBlock}
${skeletonBlock}

INTERVENTION FRAMING — for the "what_this_changes" section:
${brief.intervention_framing}

CTA — use verbatim or paraphrase without changing the ask:
${brief.cta}

---
Write the 6 sections. Return JSON only.`;

  if (brief.revision_instructions) {
    const rev = brief.revision_instructions;
    const issues = rev.specific_issues.map(i => `- ${i}`).join("\n");
    prompt += `\n\nREVISION REQUIRED — Attempt ${rev.attempt_number + 1}. Your previous memo failed quality review. Fix these specific issues:\n${issues}\n\nFounder pushback to address: ${rev.founder_pushback_context}`;
  }

  return prompt;
}

// ---------------------------------------------------------------------------
// LLM client
// ---------------------------------------------------------------------------

function getClient(injected?: Anthropic): Anthropic {
  if (injected) return injected;
  const key = process.env["ANTHROPIC_API_KEY"];
  if (!key) {
    throw new Error("ANTHROPIC_API_KEY is not set — cannot write memo");
  }
  return new Anthropic({ apiKey: key });
}

// ---------------------------------------------------------------------------
// Response parsing (exported for testing)
// ---------------------------------------------------------------------------

type RawSections = Record<LLMSectionName, string>;

export function parseResponse(text: string): RawSections {
  const cleaned = text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/, "")
    .trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    throw new Error(
      `ERR_MEMO_PARSE: LLM response was not valid JSON.\n\nResponse received:\n${text.slice(0, 500)}`
    );
  }

  if (typeof parsed !== "object" || parsed === null) {
    throw new Error("ERR_MEMO_PARSE: LLM response is not a JSON object");
  }

  const obj = parsed as Record<string, unknown>;
  const missing = LLM_SECTION_ORDER.filter(
    s => typeof obj[s] !== "string" || (obj[s] as string).trim().length === 0
  );
  if (missing.length > 0) {
    throw new Error(
      `ERR_MEMO_MISSING_SECTIONS: LLM response is missing required sections: ${missing.join(", ")}`
    );
  }

  return {
    executive_thesis: (obj["executive_thesis"] as string).trim(),
    what_we_observed: (obj["what_we_observed"] as string).trim(),
    the_pattern: (obj["the_pattern"] as string).trim(),
    what_this_means: (obj["what_this_means"] as string).trim(),
    what_this_changes: (obj["what_this_changes"] as string).trim(),
    cta: (obj["cta"] as string).trim(),
  };
}

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

function buildTitleBlock(brief: MemoBrief): MemoSection {
  const date = new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });
  const markdown = `${brief.target_company}\nStrategic Diagnostic\n${date} | Confidential`;
  return {
    name: "title_block",
    markdown,
    word_count: countWords(markdown),
  };
}

function assembleSections(raw: RawSections, brief: MemoBrief): MemoSection[] {
  const titleBlock = buildTitleBlock(brief);
  const llmSections = LLM_SECTION_ORDER.map(name => ({
    name: name as MemoSectionName,
    markdown: raw[name],
    word_count: countWords(raw[name]),
  }));
  return [titleBlock, ...llmSections];
}

function assembleMarkdown(sections: MemoSection[]): string {
  return sections
    .map(s => {
      const heading = SECTION_HEADINGS[s.name];
      return heading ? `${heading}\n\n${s.markdown}` : s.markdown;
    })
    .join("\n\n");
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function validateMemo(
  wordCount: number,
  evidenceIds: string[],
  markdown: string,
  bannedPhrases: string[]
): void {
  if (wordCount < 400) {
    throw new Error(
      `ERR_MEMO_TOO_SHORT: memo word count is ${wordCount} (minimum 400)`
    );
  }
  if (wordCount > 1400) {
    throw new Error(
      `ERR_MEMO_TOO_LONG: memo word count is ${wordCount} (hard max 1400)`
    );
  }
  if (evidenceIds.length === 0) {
    throw new Error("ERR_MEMO_EVIDENCE_EMPTY: evidence_ids is empty");
  }
  const hit = findBannedPhrase(markdown, bannedPhrases);
  if (hit) {
    throw new Error(`ERR_BANNED_PHRASE: banned phrase detected in memo: "${hit}"`);
  }
}

// ---------------------------------------------------------------------------
// Main entry
// ---------------------------------------------------------------------------

/**
 * Generate the founder-facing strategic memo from the brief.
 *
 * LLM stage — the writer is a renderer, not a reasoner.
 *
 * @param brief      - MemoBrief produced by buildMemoBrief()
 * @param attemptNumber - 1 (first attempt) or 2 (revision after critic)
 * @param config     - Optional model/client overrides; inject client in tests
 *
 * Throws:
 *   ERR_ADJUDICATION_ABORT    — brief.adjudication_mode === "abort"
 *   ERR_MEMO_PARSE            — LLM response is not parseable JSON
 *   ERR_MEMO_MISSING_SECTIONS — one or more required sections absent
 *   ERR_MEMO_TOO_LONG         — word_count > 1400
 *   ERR_MEMO_TOO_SHORT        — word_count < 400
 *   ERR_MEMO_EVIDENCE_EMPTY   — evidence_ids is empty
 *   ERR_BANNED_PHRASE         — banned phrase detected in output
 */
export async function writeMemo(
  brief: MemoBrief,
  attemptNumber: 1 | 2 = 1,
  config: WriteMemoConfig = {}
): Promise<MarkdownMemo> {
  if (brief.adjudication_mode === "abort") {
    throw new Error(
      `ERR_ADJUDICATION_ABORT: cannot write memo for company '${brief.company_id}' — adjudication mode is 'abort'`
    );
  }

  const client = getClient(config.client);
  const model = config.model ?? DEFAULT_MODEL;
  const maxTokens = config.max_tokens ?? DEFAULT_MAX_TOKENS;
  const temperature = config.temperature ?? DEFAULT_TEMPERATURE;

  const systemPrompt = buildSystemPrompt(brief);
  const userPrompt = buildUserPrompt(brief);

  const message = await client.messages.create({
    model,
    max_tokens: maxTokens,
    temperature,
    system: systemPrompt,
    messages: [{ role: "user", content: userPrompt }],
  });

  const content = message.content[0];
  if (!content || content.type !== "text") {
    throw new Error("ERR_MEMO_PARSE: LLM returned no text content");
  }

  const raw = parseResponse(content.text);
  const sections = assembleSections(raw, brief);
  const markdown = assembleMarkdown(sections);
  const wordCount = countWords(markdown);

  // evidence_ids are populated from the brief's evidence_spine (deterministic — not from LLM)
  const evidenceIds = brief.evidence_spine.map(r => r.evidence_id);

  validateMemo(wordCount, evidenceIds, markdown, brief.banned_phrases);

  const sectionWordCounts = Object.fromEntries(sections.map(s => [s.name, s.word_count]));
  console.log(JSON.stringify({
    event: "memo_generated",
    company_id: brief.company_id,
    attempt_number: attemptNumber,
    word_count: wordCount,
    section_word_counts: sectionWordCounts,
    evidence_spine_count: brief.evidence_spine.length,
  }));

  const timestamp = Date.now();
  return {
    memo_id: `memo_${brief.company_id}_${timestamp}`,
    company_id: brief.company_id,
    brief_id: brief.brief_id,
    adjudication_mode: brief.adjudication_mode,
    diagnosis_id: brief.diagnosis_id,
    intervention_id: brief.intervention_id,
    evidence_ids: evidenceIds,
    word_count: wordCount,
    attempt_number: attemptNumber,
    sections,
    markdown,
    generated_at: new Date().toISOString(),
  };
}
