/**
 * Write Memo — V3-M4 (Dean & Wiseman execution spec)
 * Spec: docs/specs/intelligence-engine-v3/005_memo_spec.md (Sub-Stage B)
 *
 * Generates the founder-facing strategic memo from the MemoBrief.
 * LLM stage — the writer is a renderer, not a reasoner.
 * All reasoning has been done upstream; the LLM renders it into prose.
 *
 * 7 sections (Dean & Wiseman execution spec):
 *   1. title_block        — code-generated (company name, date, confidential)
 *   2. executive_thesis   — the core contradiction + commercial implication
 *   3. what_we_observed   — 5-7 concrete evidence signals
 *   4. the_pattern        — the underlying system connecting the signals
 *   5. what_this_means    — business impact (trust, conversion, revenue)
 *   6. what_this_changes  — strategic shift (direction, not tactics)
 *   7. cta                — conditional framing, low-friction next step
 *
 * Model: claude-opus-4-6
 * Max tokens: 4000
 * Temperature: 0.5
 *
 * Validation: too_short < 400, too_long > 1400
 *
 * Errors:
 *   ERR_ADJUDICATION_ABORT  — adjudication_mode is "abort"
 *   ERR_MEMO_PARSE          — LLM response is not valid JSON or missing sections
 *   ERR_MEMO_MISSING_SECTIONS — one or more required sections absent
 *   ERR_MEMO_TOO_LONG       — word_count > 1400
 *   ERR_MEMO_TOO_SHORT      — word_count < 400
 *   ERR_MEMO_EVIDENCE_EMPTY — evidence_ids is empty
 *   ERR_BANNED_PHRASE       — banned phrase detected in output
 */

import Anthropic from "@anthropic-ai/sdk";
import type { MemoBrief, MemoSectionName } from "../types/memo-brief.js";
import type { LLMSectionName } from "../types/memo-brief.js";
import type { MarkdownMemo, MemoSection } from "../types/memo.js";
import { countWords } from "./utils.js";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const DEFAULT_MODEL = "claude-opus-4-6";
const DEFAULT_MAX_TOKENS = 4000;
const DEFAULT_TEMPERATURE = 0.5;

export interface WriteMemoConfig {
  model?: string;
  max_tokens?: number;
  temperature?: number;
  /** Injected Anthropic client — used in tests to avoid live API calls */
  client?: Anthropic;
}

// ---------------------------------------------------------------------------
// Section ordering and headings
// ---------------------------------------------------------------------------

/** Sections generated by the LLM (6 keys in JSON output). */
const LLM_SECTION_ORDER: LLMSectionName[] = [
  "executive_thesis",
  "what_we_observed",
  "the_pattern",
  "what_this_means",
  "what_this_changes",
  "cta",
];

/** All 7 memo sections in output order (title_block is code-generated). */
const SECTION_ORDER: MemoSectionName[] = [
  "title_block",
  ...LLM_SECTION_ORDER,
];

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function findBannedPhrase(text: string, bannedPhrases: string[]): string | null {
  const lower = text.toLowerCase();
  for (const phrase of bannedPhrases) {
    if (lower.includes(phrase.toLowerCase())) {
      return phrase;
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Framing instruction by adjudication_mode
// ---------------------------------------------------------------------------

function framingInstruction(mode: string): string {
  switch (mode) {
    case "full_confidence":
      return "State the diagnosis directly as established fact. Do not hedge. The evidence is strong.";
    case "conditional":
      return "State the diagnosis with confidence, but qualify briefly where evidence is inferred. Be direct where evidence is strong.";
    case "exploratory":
      return "Frame the diagnosis as a hypothesis. Use language like 'the evidence suggests', 'this may indicate', or 'there are signs that'. Do not state anything as established fact.";
    default:
      return "State the diagnosis with care appropriate to the evidence available.";
  }
}

// ---------------------------------------------------------------------------
// System prompt (exported for testing)
// ---------------------------------------------------------------------------

export function buildSystemPrompt(brief: MemoBrief): string {
  const bannedSample = brief.banned_phrases.join(", ");
  const caveats =
    brief.confidence_caveats.length > 0
      ? `\nDo not assert the following as established fact: ${brief.confidence_caveats.join("; ")}.`
      : "";

  // V4 system prompt additions — included when synthesis fields are active
  const synthActive =
    brief.synthesised_thesis !== undefined &&
    brief.mechanism_narratives !== undefined &&
    brief.argument_skeleton !== undefined;

  const v4Rules = synthActive
    ? `\n6. The COMPANY-SPECIFIC DIAGNOSTIC STATEMENT names the GTM condition AND its commercial consequence. Use it as-is or paraphrase — do not generalise.\n7. The CAUSAL MECHANISMS are company-specific. Render them; do not rewrite into generic descriptions.\n8. The SUGGESTED ARGUMENT FLOW orders evidence into the strongest logical sequence. Follow unless a superior structure presents itself.\n9. The HOOK STRATEGY tells you what tension to create. Honor the tension_type.`
    : "";

  const hedgingBan =
    brief.adjudication_mode === "full_confidence"
      ? `\nHEDGING BAN: Do not use "likely", "may indicate", "could be", "might", "it is possible", "the evidence leaves this open". State findings with the confidence the evidence warrants.`
      : brief.adjudication_mode === "conditional"
        ? `\nHEDGING RULE: Hedge the diagnosis itself ("the evidence suggests", "if this pattern holds"), but state every implication with full conviction. Never hedge both the diagnosis and its consequence in the same sentence.`
        : "";

  return `You are writing a Dean & Wiseman strategic diagnostic. A letter to a specific person who did not ask for it, who is busy, who has seen a hundred pitches this month, and who will give you four sentences to prove you are worth the next four. It will be printed and mailed as a physical object. Every word must earn its place on paper.

THE THREE EFFECTS: every memo must produce all three:
1. RECOGNITION: "That's uncomfortably accurate"
2. SURPRISE: "I hadn't seen it like that"
3. CURIOSITY: "There's a clear way forward. I want to hear it."

THE LAWS:

LAW 1 -- THE FIRST SENTENCE EARNS THE SECOND.
Open with a customer's own words about the company, or a specific verifiable fact about their business, or a claim that contradicts their assumptions. Do not open with the company's own positioning, industry context, or anything the reader already knows. Do not introduce yourself. Do not compliment them.

LAW 2 -- BE SPECIFIC OR BE QUIET.
Every claim must pass the swap test: remove the company name. If the sentence could describe any other company, it is too abstract. Replace every abstraction with a person in a room making a decision. Not "mid-market operations leaders evaluating tools in a 2-4 week cycle" -- instead: "A head of support at a 200-person SaaS company can trial the product on a Monday and show her CEO the resolution data by Friday."

LAW 3 -- RHYTHM IS MEANING.
Read every paragraph aloud. If every sentence takes the same number of breaths, rewrite. Follow a long, careful sentence with a short, blunt one. Let some paragraphs be a single sentence. No two consecutive sentences should be within three words of each other in length. Banned: three or more consecutive sentences of similar length or similar syntactic structure.

LAW 4 -- HAVE A VIEW. RISK BEING WRONG.
Hedge the data, not the interpretation. "We don't have your conversion numbers" is honest. "The evidence suggests a potential misalignment" is evasive. If the evidence points one direction, say so. Delete every qualifier. Read what remains. If it's defensible with the evidence you have, use it.

LAW 5 -- ONE UNCOMFORTABLE SENTENCE.
Every memo must contain one sentence that names a cost the company cannot see from inside. Specific enough that the reader's first reaction is discomfort and their second is "they're right." This is the sentence that earns the meeting.

LAW 6 -- NEVER PERFORM BALANCE YOU DON'T BELIEVE.
If the evidence points one direction, don't write "that said" or "on the other hand." One honest "we don't know" is worth more than ten artificial counterpoints. Banned: "That said." "On the other hand." "It could also be the case that."

LAW 7 -- WRITE TO THE ONE READER.
You're not introducing a problem. You're naming something the founder already feels. Never explain what the company does. Never provide industry context they already have. Start inside their experience. The first time the reader feels educated rather than understood, they stop reading.

LAW 8 -- THE STRUCTURE MUST BE INVISIBLE.
Do not use generic headers. If you use headers, make them specific to this company and this argument. "What [Company]'s customers say versus what [Company]'s marketing says" has content. "What We Observed" has only structure. Better still: let the argument flow as continuous prose.

LAW 9 -- SHOW THE MECHANISM, THEN NAME IT.
Before naming any strategic concept, construct a scenario the reader can feel. Two prospect paths. A buyer's internal conversation. Let the scenario carry the persuasive weight, then name the mechanism in plain language a founder could use in their next meeting.

LAW 10 -- EVERY MEMO MUST FEEL HANDMADE.
No two memos may share identical section headers, closing language, or transitional phrases. Every memo must contain at least one observation, one turn of phrase, one structural choice that could not appear in any other memo.

LAW 11 -- RESPECT THE READER'S TIME.
Every sentence must advance the argument or be cut. No restating. No summarising what you've already said. No transitional sentences that exist only to connect paragraphs. Delete any sentence you suspect is padding.

LAW 12 -- BRITISH ENGLISH. NO EM DASHES.
British English in all cases. Colour, not color. Recognise, not recognize. No em dashes under any circumstances. Use full stops, commas, colons, semicolons, or restructure the sentence. Never use a semicolon more than once per section.

LAW 13 -- USE CONTRACTIONS.
Use contractions naturally. "It's" not "It is." "Don't" not "Do not." "We're" not "We are." Formal avoidance of contractions is an AI tell. Real strategic writing at a senior level uses contractions.

LAW 14 -- THE SLIPPERY SLIDE.
Every element makes the reader read the next. The first sentence makes them read the second. The diagnosis section makes them read the prescription. The prescription makes them read the CTA. Use at most two or three seeds of curiosity per document ("and this is where it gets interesting", "but the data tells a different story"). More than that and they become visible as a technique.

LAW 15 -- SENTENCE LENGTH VARIANCE.
After drafting any paragraph, verify that no two consecutive sentences are within three words of each other in length. A good paragraph might contain sentences of 6, 22, 4, 18, and 11 words. That kind of variance is the heartbeat of human prose.

LAW 16 -- DIAGNOSIS BEFORE PRESCRIPTION.
This document is 80% diagnosis, 20% prescription. The founder does not yet trust you. What they will recognise, instantly, is whether you understand their problem. Never lead with solution. The prescription is only the doorway to a conversation.

LAW 17 -- HONESTY AS PERSUASION.
If the data shows something working well, say so. "Your product-led motion is actually working. Your activation rates suggest the product sells itself once people try it. The problem is upstream." The moments of honesty make the moments of diagnosis land harder, not softer.

LAW 18 -- NO TRICOLON.
Never use three-part rhythm lists. "We analyse, we strategise, and we execute." "It's fast, it's reliable, and it's affordable." These patterns are deeply embedded in AI training data. Break the pattern. Use two items. Or four. Or just make a statement.

LAW 19 -- VARY PARAGRAPH STRUCTURE.
Never use the topic-sentence + three-supporting-points paragraph structure. This is textbook essay format. Vary paragraph architecture. Some paragraphs are one sentence. Some are five. Some open with evidence and end with interpretation. Some do the reverse.

LAW 20 -- PHYSICAL OBJECT RULE.
This document will be printed and held in someone's hands. No filler. No padding. No warming-up paragraphs. Paper is more intimate than a screen. Every word must justify its presence.

WRITING ANTI-PATTERNS -- signatures of AI-generated text. Never use them:
- Transition openers: "Furthermore", "Moreover", "Additionally", "Notably", "Importantly", "Indeed", "Crucially".
- Throat-clearing: "It's worth noting that", "It bears mentioning", "It is important to recognize", "It goes without saying".
- Demonstrative fillers: "This represents", "This demonstrates", "This underscores", "This highlights", "This speaks to".
- Dead words: "delve", "tapestry", "utilize", "harness", "bolster", "garner", "synergy", "myriad", "plethora", "holistic", "nuanced", "robust", "comprehensive", "seamless", "leverage", "foster", "landscape", "paradigm", "groundbreaking", "cutting-edge", "streamline", "elevate", "empower", "encompass", "multifaceted", "endeavour", "beacon", "realm", "illuminate", "resonate", "interplay", "commendable", "cornerstone", "spearhead", "bustling", "aforementioned", "henceforth".
- Phrase patterns: "In today's...", "At its core...", "In the realm of...", "When it comes to...", "Navigating the complexities of...", "A testament to...", "In an era of...", "Moving forward", "In conclusion", "To summarize", "Without further ado".
- Performative balance: "That said", "On the other hand", "It could also be the case that".
- Do not open three or more consecutive sentences with the same word.
- Do not use colons to introduce inline lists more than once per section.

EVIDENCE TEXTURE:
Weave specific language from evidence into the analytical narrative. Use review excerpts, developer comments, pricing page phrasing, and job post language as texture within sentences, not as standalone quotes. Example: instead of 'Customers value speed', write 'Multiple reviews describe the product as "the fastest way to get a PO signed", language that never appears on the company's pricing page.' This is the difference between a memo that feels researched and one that feels generated.

SECTION-BY-SECTION GUIDANCE:

executive_thesis (80-130w):
Open with customer language or a specific verifiable fact. Define the core contradiction. Create immediate tension. Surface reality vs underlying reality vs what it costs the founder. Reader should think: "That's uncomfortably accurate."

what_we_observed (180-260w):
5-7 concrete signals. Weave specific language from evidence (review excerpts, developer comments, pricing page phrasing) into the narrative as texture, not block quotes. Every observation must support the thesis. Reader should think: "They've actually looked at this properly."

the_pattern (130-200w):
The underlying system. One unifying idea. Show the mechanism before naming it. The structural forces woven into the narrative, not labelled. Reader should think: "I hadn't seen it like that."

what_this_means (140-200w):
Business impact. Name specific commercial consequences the founder can estimate. No exaggeration. No precise numbers unless proven. Reader should think: "This is likely costing us."

what_this_changes (140-200w):
Strategic direction, not tactics. Clear but incomplete. The founder should think "there's a clear way forward" but not "I understand the whole playbook."

cta (40-70w):
Convert interest into conversation. Conditional framing. Low friction. No pressure. No sales language. Only section allowed to use first person.

HARD RULES:
1. Do not invent any facts.
2. Do not use banned phrases: ${bannedSample}.
3. Do not use internal labels ("diagnosis", "mechanism", "intervention", "evidence_spine").
4. Do not open with a compliment, question, or "I wanted to reach out" phrasing.
5. Do not name specific pricing, product tiers, or implementation costs.${caveats}${v4Rules}

${framingInstruction(brief.adjudication_mode)}
${hedgingBan}

WORD BUDGET: Target ${brief.word_budget.target_min}-${brief.word_budget.target_max} words total. Hard maximum: ${brief.word_budget.hard_max}.
Section targets: executive_thesis (80-130w), what_we_observed (180-260w), the_pattern (130-200w), what_this_means (140-200w), what_this_changes (140-200w), cta (40-70w).

OUTPUT FORMAT: Return valid JSON only. No markdown code fences. No text outside the JSON object.
The JSON must have exactly these 12 keys. The 6 content keys are required and must not be empty. The 6 header keys are optional -- write a company-specific header that adds information, or return an empty string if you cannot:
{
  "executive_thesis_header": "company-specific header or empty string",
  "executive_thesis": "...",
  "what_we_observed_header": "company-specific header or empty string",
  "what_we_observed": "...",
  "the_pattern_header": "company-specific header or empty string",
  "the_pattern": "...",
  "what_this_means_header": "company-specific header or empty string",
  "what_this_means": "...",
  "what_this_changes_header": "company-specific header or empty string",
  "what_this_changes": "...",
  "cta_header": "company-specific header or empty string",
  "cta": "..."
}
Each content value is the full prose for that section (plain text, use \\n\\n for paragraph breaks within a section).`;
}

// ---------------------------------------------------------------------------
// User prompt (exported for testing)
// ---------------------------------------------------------------------------

export function buildUserPrompt(brief: MemoBrief): string {
  const founderLine = brief.founder_name
    ? `Founder: ${brief.founder_name}${brief.founder_title ? `, ${brief.founder_title}` : ""}\n`
    : "";

  const spineLines = brief.evidence_spine
    .map((r, i) => `  [${i + 1}] "${r.excerpt}"\n      Section guidance: ${r.usage_instruction}`)
    .join("\n");

  // V4 context blocks — built when synthesis fields are present in brief
  const synthActive =
    brief.synthesised_thesis !== undefined &&
    brief.mechanism_narratives !== undefined &&
    brief.argument_skeleton !== undefined &&
    brief.hook_strategy !== undefined;

  const hookStrategyBlock = synthActive
    ? `\nHOOK STRATEGY — understand the strategic intent before rendering:
  Evidence anchor: ${brief.hook_strategy!.evidence_id}
  Tension type: ${brief.hook_strategy!.tension_type}
  Framing instruction: ${brief.hook_strategy!.framing}
  Why this matters to the founder: ${brief.hook_strategy!.why_it_matters}`
    : "";

  const thesisBlock = synthActive
    ? `COMPANY-SPECIFIC DIAGNOSTIC STATEMENT — use this as the thesis:
  ${brief.synthesised_thesis!}
  (This names the specific GTM condition, anchored in an observable company fact,
   and its commercial consequence. Use it as the basis for "what_this_means".
   Do not generalise it.)`
    : `THESIS — the central commercial claim to argue:
${brief.thesis}`;

  const mechanismsBlock =
    synthActive && brief.mechanism_narratives!.length >= 2
      ? `\nCAUSAL MECHANISMS — use these company-specific narratives in "the_pattern":
  Force 1 (${brief.mechanism_narratives![0].mechanism_type}): ${brief.mechanism_narratives![0].company_specific_narrative}
    Evidence: ${brief.mechanism_narratives![0].evidence_refs.join(", ")}
  Force 2 (${brief.mechanism_narratives![1].mechanism_type}): ${brief.mechanism_narratives![1].company_specific_narrative}
    Evidence: ${brief.mechanism_narratives![1].evidence_refs.join(", ")}`
      : "";

  const skeletonBlock =
    synthActive && brief.argument_skeleton!.length > 0
      ? `\nSUGGESTED ARGUMENT FLOW — structure the argument in this order (advisory):\n${
          brief.argument_skeleton!
            .map(
              s =>
                `  Step ${s.step_order} [${s.logical_role}]: Evidence ${s.evidence_id} — ${s.purpose}${s.connector ? ` (${s.connector})` : ""}`
            )
            .join("\n")
        }\n  (The step marked [diagnosis] connects observation and mechanisms into the thesis.)`
      : "";

  let prompt = `Write a 6-section Dean & Wiseman strategic diagnostic for the following company.

COMPANY: ${brief.target_company}
${founderLine}
OPENING HOOK — anchor the Executive Thesis section with this:
Excerpt: "${brief.hook.excerpt}"
Framing instruction: ${brief.hook.framing_instruction}
${hookStrategyBlock}

${thesisBlock}

EVIDENCE SPINE — the only facts you may use (do not invent beyond these):
${spineLines}
${mechanismsBlock}
${skeletonBlock}

INTERVENTION FRAMING — for the "what_this_changes" section:
${brief.intervention_framing}

CTA — preserve the mechanism (reframe being wrong as informative, name what the meeting would test, keep to twenty minutes) but craft the specific language to feel individually written for ${brief.target_company}. Do not reuse phrasing from any template. The closing must feel like it was written once, for this company only.
Base mechanism: ${brief.cta}

---
Write the 6 sections. Return JSON only.`;

  if (brief.revision_instructions) {
    const rev = brief.revision_instructions;
    const issues = rev.specific_issues.map(i => `- ${i}`).join("\n");
    prompt += `\n\nREVISION REQUIRED — Attempt ${rev.attempt_number + 1}. Your previous memo failed quality review. Fix these specific issues:\n${issues}\n\nFounder pushback to address: ${rev.founder_pushback_context}\n\nOutput JSON only. No explanation or preamble.`;
  }

  if (brief.rory_revision_notes) {
    const rory = brief.rory_revision_notes;
    const suggestions = rory.specific_suggestions.map(s => `- ${s}`).join("\n");
    prompt += `\n\nRORY SUTHERLAND REVISION NOTES — Your previous memo was not strategically interesting enough. Rory's feedback:\n\nWhat is boring: ${rory.what_is_boring}\nWhat would be interesting: ${rory.what_would_be_interesting}\nMissing behavioural layer: ${rory.missing_behavioural_layer}\n\nSpecific suggestions:\n${suggestions}`;
  }

  return prompt;
}

// ---------------------------------------------------------------------------
// LLM client
// ---------------------------------------------------------------------------

function getClient(injected?: Anthropic): Anthropic {
  if (injected) return injected;
  const key = process.env["ANTHROPIC_API_KEY"];
  if (!key) {
    throw new Error("ANTHROPIC_API_KEY is not set — cannot write memo");
  }
  return new Anthropic({ apiKey: key });
}

// ---------------------------------------------------------------------------
// Response parsing (exported for testing)
// ---------------------------------------------------------------------------

type RawSections = Record<LLMSectionName, string> & {
  executive_thesis_header?: string;
  what_we_observed_header?: string;
  the_pattern_header?: string;
  what_this_means_header?: string;
  what_this_changes_header?: string;
  cta_header?: string;
};

/**
 * Sanitize an LLM-generated section header value.
 * - Non-string or absent → undefined (suppress ## line)
 * - Empty or whitespace-only → undefined
 * - Strips leading # characters (LLM may prefix with ##)
 * - Replaces embedded newlines with a space
 */
function sanitizeHeader(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim().replace(/^#+\s*/, "").replace(/\n/g, " ").trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

export function parseResponse(text: string): RawSections {
  const cleaned = text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/, "")
    .trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    // Fallback: extract JSON object from surrounding text (handles LLM thinking-text preamble)
    const jsonStart = cleaned.indexOf("{");
    const jsonEnd = cleaned.lastIndexOf("}");
    if (jsonStart !== -1 && jsonEnd > jsonStart) {
      try {
        parsed = JSON.parse(cleaned.slice(jsonStart, jsonEnd + 1));
      } catch {
        throw new Error(
          `ERR_MEMO_PARSE: LLM response was not valid JSON.\n\nResponse received:\n${text.slice(0, 500)}`
        );
      }
    } else {
      throw new Error(
        `ERR_MEMO_PARSE: LLM response was not valid JSON.\n\nResponse received:\n${text.slice(0, 500)}`
      );
    }
  }

  if (typeof parsed !== "object" || parsed === null) {
    throw new Error("ERR_MEMO_PARSE: LLM response is not a JSON object");
  }

  const obj = parsed as Record<string, unknown>;
  const missing = LLM_SECTION_ORDER.filter(
    s => typeof obj[s] !== "string" || (obj[s] as string).trim().length === 0
  );
  if (missing.length > 0) {
    throw new Error(
      `ERR_MEMO_MISSING_SECTIONS: LLM response is missing required sections: ${missing.join(", ")}`
    );
  }

  return {
    executive_thesis: (obj["executive_thesis"] as string).trim(),
    what_we_observed: (obj["what_we_observed"] as string).trim(),
    the_pattern: (obj["the_pattern"] as string).trim(),
    what_this_means: (obj["what_this_means"] as string).trim(),
    what_this_changes: (obj["what_this_changes"] as string).trim(),
    cta: (obj["cta"] as string).trim(),
    executive_thesis_header: sanitizeHeader(obj["executive_thesis_header"]),
    what_we_observed_header: sanitizeHeader(obj["what_we_observed_header"]),
    the_pattern_header: sanitizeHeader(obj["the_pattern_header"]),
    what_this_means_header: sanitizeHeader(obj["what_this_means_header"]),
    what_this_changes_header: sanitizeHeader(obj["what_this_changes_header"]),
    cta_header: sanitizeHeader(obj["cta_header"]),
  };
}

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

function buildTitleBlock(brief: MemoBrief): MemoSection {
  const date = new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });
  const markdown = `${brief.target_company}\nStrategic Diagnostic\n${date} | Confidential`;
  return {
    name: "title_block",
    markdown,
    word_count: countWords(markdown),
  };
}

function assembleSections(raw: RawSections, brief: MemoBrief): MemoSection[] {
  const titleBlock = buildTitleBlock(brief);
  const llmSections = LLM_SECTION_ORDER.map(name => ({
    name: name as MemoSectionName,
    header: raw[`${name}_header` as keyof RawSections] as string | undefined,
    markdown: raw[name],
    word_count: countWords(raw[name]),
  }));
  return [titleBlock, ...llmSections];
}

function assembleMarkdown(sections: MemoSection[]): string {
  return sections
    .map(s => {
      if (s.name === "title_block") return s.markdown;
      return s.header
        ? `## ${s.header}\n\n${s.markdown}`
        : s.markdown;
    })
    .join("\n\n");
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function validateMemo(
  wordCount: number,
  evidenceIds: string[],
  markdown: string,
  bannedPhrases: string[]
): void {
  if (wordCount < 400) {
    throw new Error(
      `ERR_MEMO_TOO_SHORT: memo word count is ${wordCount} (minimum 400)`
    );
  }
  if (wordCount > 1400) {
    throw new Error(
      `ERR_MEMO_TOO_LONG: memo word count is ${wordCount} (hard max 1400)`
    );
  }
  if (evidenceIds.length === 0) {
    throw new Error("ERR_MEMO_EVIDENCE_EMPTY: evidence_ids is empty");
  }
  const hit = findBannedPhrase(markdown, bannedPhrases);
  if (hit) {
    throw new Error(`ERR_BANNED_PHRASE: banned phrase detected in memo: "${hit}"`);
  }
}

// ---------------------------------------------------------------------------
// Main entry
// ---------------------------------------------------------------------------

/**
 * Generate the founder-facing strategic memo from the brief.
 *
 * LLM stage — the writer is a renderer, not a reasoner.
 *
 * @param brief      - MemoBrief produced by buildMemoBrief()
 * @param attemptNumber - 1 (first attempt) or 2 (revision after critic)
 * @param config     - Optional model/client overrides; inject client in tests
 *
 * Throws:
 *   ERR_ADJUDICATION_ABORT    — brief.adjudication_mode === "abort"
 *   ERR_MEMO_PARSE            — LLM response is not parseable JSON
 *   ERR_MEMO_MISSING_SECTIONS — one or more required sections absent
 *   ERR_MEMO_TOO_LONG         — word_count > 1400
 *   ERR_MEMO_TOO_SHORT        — word_count < 400
 *   ERR_MEMO_EVIDENCE_EMPTY   — evidence_ids is empty
 *   ERR_BANNED_PHRASE         — banned phrase detected in output
 */
export async function writeMemo(
  brief: MemoBrief,
  attemptNumber: 1 | 2 | 3 = 1,
  config: WriteMemoConfig = {}
): Promise<MarkdownMemo> {
  if (brief.adjudication_mode === "abort") {
    throw new Error(
      `ERR_ADJUDICATION_ABORT: cannot write memo for company '${brief.company_id}' — adjudication mode is 'abort'`
    );
  }

  const client = getClient(config.client);
  const model = config.model ?? DEFAULT_MODEL;
  const maxTokens = config.max_tokens ?? DEFAULT_MAX_TOKENS;
  const temperature = config.temperature ?? DEFAULT_TEMPERATURE;

  const systemPrompt = buildSystemPrompt(brief);
  const userPrompt = buildUserPrompt(brief);

  const message = await client.messages.create({
    model,
    max_tokens: maxTokens,
    temperature,
    system: systemPrompt,
    messages: [{ role: "user", content: userPrompt }],
  });

  const content = message.content[0];
  if (!content || content.type !== "text") {
    throw new Error("ERR_MEMO_PARSE: LLM returned no text content");
  }

  const raw = parseResponse(content.text);
  const sections = assembleSections(raw, brief);
  const markdown = assembleMarkdown(sections);
  const wordCount = countWords(markdown);

  // evidence_ids are populated from the brief's evidence_spine (deterministic — not from LLM)
  const evidenceIds = brief.evidence_spine.map(r => r.evidence_id);

  try {
    validateMemo(wordCount, evidenceIds, markdown, brief.banned_phrases);
  } catch (err) {
    if (err instanceof Error && err.message.startsWith("ERR_BANNED_PHRASE")) {
      console.log(JSON.stringify({
        event: "banned_phrase_rejected",
        company_id: brief.company_id,
        attempt_number: attemptNumber,
        error: err.message,
      }));
    }
    throw err;
  }

  const sectionWordCounts = Object.fromEntries(sections.map(s => [s.name, s.word_count]));
  console.log(JSON.stringify({
    event: "memo_generated",
    company_id: brief.company_id,
    attempt_number: attemptNumber,
    word_count: wordCount,
    section_word_counts: sectionWordCounts,
    evidence_spine_count: brief.evidence_spine.length,
  }));

  const timestamp = Date.now();
  return {
    memo_id: `memo_${brief.company_id}_${timestamp}`,
    company_id: brief.company_id,
    brief_id: brief.brief_id,
    adjudication_mode: brief.adjudication_mode,
    diagnosis_id: brief.diagnosis_id,
    intervention_id: brief.intervention_id,
    evidence_ids: evidenceIds,
    word_count: wordCount,
    attempt_number: attemptNumber,
    sections,
    markdown,
    generated_at: new Date().toISOString(),
  };
}
